FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD mtest-art.jar /opt/mtest-art/
EXPOSE 8080
WORKDIR /opt/mtest-art/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "mtest-art.jar"]
